config:
frontend:
mobile_app:
person:
system_health:
history:
sun:
api:
updater:

recorder:
  purge_keep_days: 3
  db_url: <redacted>/homeassistant?charset=utf8
  include:
    domains:
      - sensor

http:
  ssl_certificate: /config/ssl/fullchain.pem
  ssl_key: /config/ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

sensor:
  - platform: command_line
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    name: cputemp0
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: command_line
    command: "cat /sys/class/thermal/thermal_zone1/temp"
    name: cputemp1
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: command_line
    command: "cat /sys/class/thermal/thermal_zone2/temp"
    name: cputemp2
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: uptime
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

light:
  - platform: group
    name: Living Room Ceiling
    entities:
      - light.bulb5gu10_light
      - light.bulb6gu10_light
      - light.bulb7gu10_light
  - platform: group
    name: Bedroom Side
    entities:
      - light.bulb4rgb_light
      - light.bulb3rgb_light

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
